import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>MshTicket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-5xl text-white font-mono font-bold'>where would you <br></br> like to go?</h1>
      

      
      <div class="showcase-search">
        <div class="filters">
          <div class="filter">
            
            <div class="search-text">
              
              <h2>Sydney</h2>
            </div>
          </div>
          <div class="filter">
          
            <div class="search-text">
              
              <h2>Delhi</h2>
            </div>
          </div>
          <div class="filter">
            
            <div class="search-text">
              
              <h2>01.04.2021</h2>
            </div>
          </div>
          <div class="filter">
            
            <div class="search-text">
              
              <h2>Returning</h2>
            </div>
          </div>
          <div class="filter">
          
            <div class="search-text">
              
              <h2>1 Guest</h2>
            </div>
          </div>
          <div class="filter">
          
            <div class="search-text">
              
              <h2 className='bg-fuchsia-700 text-white'>Search Tickets</h2>
            </div>
          </div>
        </div>
        
      </div>
    </>
  )
}
